# Reload config
unbind r 
bind r source-file ~/.tmux.conf

set -g prefix C-b
unbind C-w
bind C-b send-prefix

# General settings
set-option -g status-position top
set -as terminal-overrides ',*:RGB'   # for tmux =3.2
set -g default-terminal "tmux-256color"
set -g set-clipboard on

# Toggle mouse mode with Prefix + m
bind m \
    set -g mouse \; \
    display-message "Mouse mode is now #{?mouse,on,off}"

# Go to the last session
bind-key C-l switch-client -l

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

# Vim-like pane navigation
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes and start in the same directory
bind-key v split-window -h -c "#{pane_current_path}"
bind-key b split-window -v -c "#{pane_current_path}"

# Catppuccin theme config
set -g @catppuccin_flavour "frappe"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_show_window_index "on"

# Status bar modules
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session} #{E:@catppuccin_status_application}"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
